### ISSUE TITLE
Preserve quotes when reading -> writing back YAML.

### ISSUE THREAD

**Issue by consideRatio** [sgibson91/bump-jhub-image-action#121]
It seems that this action will not retain quotes in YAML when writing YAML back, and by doing so possibly cause issues.

In https://github.com/2i2c-org/infrastructure/pull/1357/files I saw:
![image](https://user-images.githubusercontent.com/3837114/171232243-938a73ec-113f-4b1d-b344-0d5c900d901b.png)

I mention this specifically because there have been issues with content becoming parsed as integers instead of strings - sometimes. For example here, this tag could have become an integer if the single letter `b` in it had been a number instead. If that would have happened, I think the schema validation logic of the z2jh helm chart would have complained.

![image](https://user-images.githubusercontent.com/3837114/171232304-ad714d1a-2826-4e83-b175-be222affa071.png)

---

A simple resolution to this issue, as ruamel.yaml is used, is to do [like in jupyterhub/chartpress](https://github.com/jupyterhub/chartpress/blob/main/chartpress.py#L41-L45) I think.

**Comment by sgibson91** [comment]
Thanks Erik - I'm aware of this problem and am trying to fix it :)

**Comment by sgibson91** [comment]
This PR proves that the code preserves quotes, comments and indentations https://github.com/sgibson91/bump-jhub-image-action/pull/124 I'm going to purge the Docker image I think

**Comment by sgibson91** [comment]
I give up 😭  https://github.com/2i2c-org/infrastructure/pull/1373/files

**Comment by consideRatio** [comment]
@sgibson91 you may need to specify the type of YAML instance you want, is a round-trip one, where the YAML parser will retain information about things in the YAML file in a way that enables it to write it back.

I note a difference between the initialization of the YAML object:
- https://github.com/jupyterhub/chartpress/blob/main/chartpress.py#L41-L45
- https://github.com/sgibson91/bump-jhub-image-action/blob/56ea09ed8684cff77b7704424bb3e7001031d768/tag_bot/yaml_parser.py#L8

**Comment by sgibson91** [comment]
It is roundtrip by default and I used the same settings generate both the PR here and the one in 2i2c/infrastructure. I'm pretty sure the issue is Docker image caching - not anything to do with how the YAML instance is set up.

**Comment by sgibson91** [comment]
Swap to using `yq` and I believe we're golden!

**Comment by sgibson91** [comment]
This is a much more sensible diff generated by #126 !!! https://github.com/2i2c-org/infrastructure/pull/1376/files
